apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: uqgos7pdn-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:3a793bb963e4bbd93d655dafe2d4877552c57710@sha256:f5c1e99ca2baa93341b9ced5715ccadef7dd88448a6603a1549c9ea4e0a52695
          name: container-image
